common: &common
  docker:
    - image: unifio/ci:3.0.412-node-8.9.4

  environment:
     DOCKER_DD_AGENT_VERSION: 12.5.5223
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *common

    steps:
     - checkout
     - setup_remote_docker:
        version: 17.11.0-ce
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
      - run:
          name: Build Docker dd-agent
          command: |
             docker build -t unifio/docker-dd-agent:${DOCKER_DD_AGENT_VERSION}.${CIRCLE_BUILD_NUM} .
      - run:
          name: Test dd-agent binaries
              docker run --entrypoint /usr/local/bin/consul unifio/docker-dd-agent version
              docker run --entrypoint /usr/local/bin/consul-template unifio/docker-dd-agent --version
      - run:
          name: Push dd-agent image to docker hub
             docker login -u $DOCKER_USER -p $DOCKER_PASS
             docker push unifio/docker-dd-agent:${DOCKER_DD_AGENT_VERSION}.${CIRCLE_BUILD_NUM}
